export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const SET_LOGIN_TOKEN = "SET_LOGIN_TOKEN";
export const REMOVE_LOGIN_TOKEN = "REMOVE_LOGIN_TOKEN";

export const SET_ALL_DOCTORS = "SET_ALL_DOCTORS";
export const SET_ALL_ORGANIZATION = "SET_ALL_ORGANIZATION";

export const SET_MAJOR_TESTS = "SET_MAJOR_TESTS";
export const ADD_MAJOR_LAB_TEST = "ADD_MAJOR_LAB_TEST";

export const SET_MINOR_TESTS = "SET_MINOR_TESTS";
export const ADD_MINOR_LAB_TEST = "ADD_MINOR_LAB_TEST";

export const LOADING = "LOADING";

export const SET_ALL_PATIENTS = "SET_ALL_PATIENTS";
export const SET_PATIENT_TEST_DETAIL = "SET_PATIENT_TEST_DETAIL";
